# Generated by Django 3.0.4 on 2020-11-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='celular',
            field=models.CharField(help_text='Com WhatsApp', max_length=10, verbose_name='Celular *'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(db_index=True, max_length=100, unique=True, verbose_name='E-mail *'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome Completo *'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('ENFERMEIRO', 'Enfermeiro'), ('USUÁRIO', 'Usuário')], default='USUÁRIO', help_text='* Campos obrigatórios', max_length=15, verbose_name='Tipo do Usuário *'),
        ),
    ]
